# Generated by Django 4.2.4 on 2023-10-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(max_length=100, verbose_name='контактная почта')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент сервис',
                'verbose_name_plural': 'клиент сервисы',
            },
        ),
        migrations.CreateModel(
            name='MessagesForDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_theme', models.CharField(max_length=100, verbose_name='тема письма')),
                ('message_body', models.TextField(verbose_name='текст письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailDistributionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.TimeField(verbose_name='время начала рассылки')),
                ('date_finish', models.TimeField(verbose_name='время окончания рассылки')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ещемесячно')], default='daily', max_length=20, verbose_name='период')),
                ('distribution_status', models.CharField(choices=[('created', 'Запущена'), ('started', 'Создана'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='статус')),
                ('clients', models.ManyToManyField(to='mail.client', verbose_name='клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.messagesfordistribution', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки')),
                ('attempt_status', models.BooleanField(choices=[('Ok', 'Успешно'), ('Failed', 'Ошибка')], default='Ok', verbose_name='статус попытки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='Клиент')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.maildistributionsettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
