# Generated by Django 4.2.4 on 2023-10-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_client_user_maildistributionsettings_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maildistributionsettings',
            name='date_finish',
        ),
    ]
