# Generated by Django 4.2.4 on 2023-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_remove_maildistributionsettings_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maildistributionsettings',
            name='distribution_status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='статус'),
        ),
    ]
