# Generated by Django 4.2.4 on 2023-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_maildistributionsettings_distribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='attempt_status',
            field=models.CharField(choices=[('Ok', 'Успешно'), ('Failed', 'Ошибка')], default='Ok', max_length=8, verbose_name='статус попытки'),
        ),
    ]
